name: flutter_app_deploy_template
description: "A new Flutter project."

version: 0.2.4+12

environment:
  sdk: '>=3.4.4 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  # Amplify
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_api: ^2.0.0

  # chart
  fl_chart: ^0.68.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # tflite for AI
  tflite_flutter: ^0.10.4

  # launch
  flutter_launcher_icons: ^0.11.0

  # for Japanese
  mecab_dart: 0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# The following section is specific to Flutter packages.
flutter:
  # the material Icons class.
  uses-material-design: true

  # assets
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/ios/
    - assets/images/android/
    - assets/models/
    - assets/test/
    - assets/ipadic/